"""empty message

Revision ID: f6b6b57794f3
Revises: dabf42ce0e13
Create Date: 2022-03-17 14:57:49.103095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6b57794f3'
down_revision = 'dabf42ce0e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('dexterity', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('constitution', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('intelligence', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('wisdom', sa.Integer(), nullable=True))
    op.add_column('character', sa.Column('charisma', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('token_exp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.drop_column('user', 'wins')
    op.drop_column('user', 'losses')
    op.drop_column('user', 'battles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('battles', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_exp')
    op.drop_column('user', 'token')
    op.drop_column('character', 'charisma')
    op.drop_column('character', 'wisdom')
    op.drop_column('character', 'intelligence')
    op.drop_column('character', 'constitution')
    op.drop_column('character', 'dexterity')
    op.drop_column('character', 'strength')
    # ### end Alembic commands ###
